In [1]:
import numpy as np

In [3]:
#O array de numpy já é preparado para diversas operações de data science e para RNA
#características: Não é dinâmico, array tipado
npArray = np.array([1, 2, 3])
print(npArray)

[1 2 3]


In [6]:
#Iniciando array com n elementos, mas com valores zerados
x = np.zeros((5))
x

array([0., 0., 0., 0., 0.])

In [7]:
#Iniciando array com n elementos, mas com valores zerados
x = np.ones((5))
x

array([1., 1., 1., 1., 1.])

In [8]:
#Criando array com arange
x = np.arange(0, 10, step=1)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
#Buscando elementos do índice x até o fim
x[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
#Criando uma matriz

x = np.array([[1, 2, 3], [1, 2, 3]])
x

array([[1, 2, 3],
       [1, 2, 3]])

In [13]:
#mostrando primeira linha
x[0]

array([1, 2, 3])

In [14]:
#mostrando primeiro elemento
x[0][0]

1

In [18]:
x = np.array([[1, 2, 3]]*10)
x

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [19]:
x[0]

array([1, 2, 3])

In [21]:
#Matriz zerada
x = np.zeros((5, 5))
x

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
#O eye faz uma matriz com a diagonal igual a 1
#O método eye recebe uma matriz quadrática (NxN), por isso passa apenas um parâmetro
x = np.eye(4)
x

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])