In [2]:
import numpy as np

#Algumas operações com array do numpy a seguir:

In [4]:
#Multiplicando um array
x*y

array([ 4, 10, 18])

In [8]:
#multiplicando e criando um array
#Por que isso irá gerar uma matriz
x = np.array([1, 2, 3]*3)
x

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [9]:
#multiplicando e criando um matriz. No caso, precisa ser um array dentro de outro array
x = np.array([[1, 2, 3]]*3)
x

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [10]:
#operações básicas

x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

#Soma
x+y

array([5, 7, 9])

In [11]:
#subtração
x-y

array([-3, -3, -3])

In [12]:
x/y

array([0.25, 0.4 , 0.5 ])

In [13]:
x*y

array([ 4, 10, 18])