In [1]:
import tensorflow as tf 
import numpy as np
import datetime
from tensorflow.keras.datasets import fashion_mnist

In [2]:
#x tem as imagens, y tem as classes referentes a classificação das imagens
(xTrain, yTrain), (xTest, yTest) = fashion_mnist.load_data()

In [3]:
#Verificando o conteúdo da base de treino
xTrain

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [4]:
#Primeira imagem: 28px X 28px, cada elemento corresponde a cor em escala RGB (0 a 255)
xTrain[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   1,
          0,   0,  13,  73,   0,   0,   1,   4,   0,   0,   0,   0,   1,
          1,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
          0,  36, 136, 127,  62,  54,   0,   0,   0,   1,   3,   4,   0,
          0,   3],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   6,
          0, 102, 204, 176, 134, 144, 123,  23,   0,   0,   0,   0,  12,
         10,   0],
       [  

In [5]:
#normalizando as imagens para tornar a escala de pixel para 0 até 1, onde 0. Isso vai representar a escala de 0 a 255 das cores
xTrain = xTrain / 255
xTest = xTest / 255

In [6]:
#Visualizando a primeira imagem
xTrain[0]

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.    

In [7]:
#Refatorando a base para ser um vetor
xTrain.shape

(60000, 28, 28)

In [8]:
#Redimensionar todas as imagens (-1), multiplicando a altura pela largura
xTrain = xTrain.reshape(-1, 28*28)
xTest = xTest.reshape(-1, 28*28)
xTrain.shape

(60000, 784)

In [9]:
#Teremos uma rede com 784 entradas, o código abaixo cria um modelo
model = tf.keras.models.Sequential()
model

In [10]:
#Adicionando a primeira camada densa (oculta) com 128 nó's, com a função relu e a camada de entrada com 784 nó's
model.add(tf.keras.layers.Dense(units=128, activation='relu', input_shape=(784, )))

In [11]:
#Fazendo dropout na camada densa: isso é para previnir de que aconteça sobre ajuste sobre do nó, fazemos isso zerando-o
#no caso, estou zerando (drop out) 20% dos nó's (26) serão zerados
model.add(tf.keras.layers.Dropout(0.2))

In [12]:
model.add(tf.keras.layers.Dense(units=10, activation='softmax'))

In [13]:
#Compilando e treinando a rede
#Adicionando um optimizador (adam) e passando como loss function e métricas a sparse_categorical..., muito utilizada em problemas categóricos diversos
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['sparse_categorical_crossentropy'])

In [14]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 128)               100480    
_________________________________________________________________
dropout (Dropout)            (None, 128)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 10)                1290      
Total params: 101,770
Trainable params: 101,770
Non-trainable params: 0
_________________________________________________________________


In [15]:
#treinando o modelo 
model.fit(xTrain, yTrain, epochs=10)

Epoch 1/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.5358 - sparse_categorical_crossentropy: 0.5358A: 2s - loss: 0.587
Epoch 2/10
1875/1875 [==============================] - 5s 2ms/step - loss: 0.4018 - sparse_categorical_crossentropy: 0.4018
Epoch 3/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3673 - sparse_categorical_crossentropy: 0.3673A: 1s - loss: 0.3703 - sparse_
Epoch 4/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3487 - sparse_categorical_crossentropy: 0.3487
Epoch 5/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3335 - sparse_categorical_crossentropy: 0.3335
Epoch 6/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3213 - sparse_categorical_crossentropy: 0.3213
Epoch 7/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3114 - sparse_categorical_crossentropy: 0.3114
Epoch 8/10
1875/1875 [==============================] - 4s 2ms/step - loss: 

In [16]:
testLoss, testAccuracy = model.evaluate(xTest, yTest)

313/313 [==============================] - 0s 2ms/step - loss: 0.3425 - sparse_categorical_crossentropy: 0.3425
